### ISSUE TITLE
Any gotchas currently?

### ISSUE THREAD

**Issue by RichardWright** [marcbachmann/opentelemetry-node-metrics#1]
I'm going to try this out tomorrow on a dev system, any gotchas I should be aware of?

btw I looked at the output from this - ValueObservers are gauges? I had no idea. The docs really don't make that obvious in open telem. Anyway, thanks for this! Any support I can help with?

**Comment by marcbachmann** [comment]
This setup is running fine on some bigger production systems since a while.
Haven't seen any issues with it yet.

Yes, ValueObservers can be used as gauge as they can be used to support a fixed value. By default they only show the last value recorded.
https://github.com/open-telemetry/opentelemetry-specification/pull/984

**Comment by marcbachmann** [comment]
Some tests would still be good in this repo 😁
